### PR TITLE
fix: adding container interfaces method

### LINKED ISSUE #135: Container interfaces commented out
Hello, thanks for making great proxmox-sdk. I see that, [containter interfaces](https://github.com/luthermonson/go-proxmox/blob/0a31b09c4fdd6a42813053a7423a56a23c378b1d/containers.go#L118) function is commented out.

For me running proxmox version `8.1.4`, the api path `/nodes/%s/lxc/%d/interfaces`, works correctly:

```bash
curl --location 'https://192.168.1.254:8006/api2/json/nodes/pve1/lxc/700/interfaces' \
--header "Authorization: $API_TOKEN" --insecure
{"data":[{"inet":"127.0.0.1/8","hwaddr":"00:00:00:00:00:00","name":"lo","inet6":"::1/128"},{"inet6":"fe80::be24:11ff:fe89:6707/64","name":"eth0","hwaddr":"bc:24:11:89:67:07","inet":"192.168.3.95/22"}]}
```

Is there any way of uncommenting this function?

### PR DESCRIPTION
**Pull request by bl4ko**
Fixes #135

### CODE REVIEW

File: containers.go [hunk 1]
```diff
@@ -115,12 +115,10 @@ func (c *Container) Feature(ctx context.Context) (hasFeature bool, err error) {
 	return feature.HasFeature, err
 }
 
-// This seems broken on the proxmox side: https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/lxc/{vmid}/interfaces
-// I wasn't able to make it work with the API. Tested on {"release":"7.3","repoid":"c3928077","version":"7.3-3"}
-// func (c *Container) Interfaces(ctx context.Context) (interfaces []string, err error) {
-// err = c.client.Get(ctx, fmt.Sprintf("/nodes/%s/lxc/%d/interfaces", c.Node, c.VMID), &interfaces)
-// return interfaces, err
-// }
+func (c *Container) Interfaces(ctx context.Context) (interfaces []*ContainerInterface, err error) {
```
Comment (luthermonson) [inline containers.go:118]: Can we add a `type ContainerInterfaces []*ContainerInterface` and have that returned instead of `[]*ContainerInterface`, it just follows the convention we've had lying around here for a while.

File: types.go [hunk 2]
```diff
@@ -666,6 +666,13 @@ type Container struct {
 	Tags    string
 }
 
+type ContainerInterface struct {
+	Hwaddr string `json:"hwaddr,omitempty`
```
Comment (luthermonson) [inline types.go:670]: I think we should rename this to `HardwareAddress` or by go "standards" it should be `HWAddr` since it's an acronym. Your choice which you prefer.

**Comment by luthermonson** [comment]
it'd be pretty easy to add a test for this since you have the output from your curl in the issue you posted. look into the mocks dir on how to set up gock and I bet you could have some asserts done fairly quickly

File: types.go (hunk 2 above)
Comment (bl4ko) [reply types.go:670]: yeah agree.

**Review by luthermonson — APPROVED** [review]

**Comment by bl4ko** [comment]
My bad, now ci should pass.
